In [116]:
import torch
# it is like scaler value
x=torch.empty(1)
print(x)

# we see three items in our vector
x=torch.empty(3)
print(x)


# let's make it 2d
x=torch.empty(2,3)
print(x)

# let's make it 3d
x=torch.empty(2,2,3)
print(x)

#create tensors with ones value
x=torch.ones(2,2)
print(x)


#create tensors with zeros value
x=torch.zeros(2,2,dtype=torch.int)
print(x.dtype)

#create tensors with zeros value
x=torch.zeros(2,2,dtype=torch.float16)
print(x.size())

tensor([7.8223e-18])
tensor([1.4424e-17, 3.1644e-41, 0.0000e+00])
tensor([[-2.0982e-19,  3.1640e-41, -3.3125e-21],
        [ 3.1640e-41,  0.0000e+00,  0.0000e+00]])
tensor([[[ 9.2372e-22,  3.1644e-41,  0.0000e+00],
         [ 1.4013e-45,  8.9683e-44,  0.0000e+00]],

        [[ 1.1210e-43,  0.0000e+00,  1.5245e-17],
         [ 3.1644e-41, -7.1912e-20,  3.1640e-41]]])
tensor([[1., 1.],
        [1., 1.]])
torch.int32
torch.Size([2, 2])


In [117]:
import torch
x=torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [120]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)
z=torch.add(x,y)
print(z)
z=x+y
print(z)

tensor([[0.0681, 0.4258],
        [0.7363, 0.6862]])
tensor([[0.3595, 0.8514],
        [0.9995, 0.0371]])
tensor([[0.4275, 1.2772],
        [1.7358, 0.7234]])
tensor([[0.4275, 1.2772],
        [1.7358, 0.7234]])


In [123]:
# in place operation
y.add_(x)
z=torch.sub(x,y)
print(z)
print(y)

tensor([[-0.4956, -1.7030],
        [-2.4721, -1.4096]])
tensor([[0.5637, 2.1288],
        [3.2084, 2.0958]])


In [124]:
# in place operation
y.add_(x)
z=torch.mul(x,y)
print(z)
print(y)

tensor([[0.0430, 1.0877],
        [2.9045, 1.9090]])
tensor([[0.6318, 2.5545],
        [3.9447, 2.7820]])


In [126]:
# in place operation
y.add_(x)
z=x/y
z=torch.div(x,y)
print(z)
print(y)

tensor([[0.0886, 0.1250],
        [0.1359, 0.1652]])
tensor([[0.7679, 3.4061],
        [5.4174, 4.1544]])


In [135]:
import torch
x=torch.rand(5,3)
print(x)
print(x[:0])
print(x[1,1].item())

tensor([[0.7684, 0.6997, 0.5237],
        [0.0581, 0.0017, 0.2142],
        [0.7168, 0.6162, 0.7755],
        [0.3724, 0.0246, 0.3900],
        [0.4023, 0.1147, 0.0520]])
tensor([], size=(0, 3))
0.0016580820083618164


In [140]:
import torch
x=torch.rand(4,4)
print(x)
y=x.view(16)
print(y)

tensor([[0.7239, 0.5007, 0.0117, 0.5318],
        [0.7377, 0.1085, 0.5643, 0.0905],
        [0.4676, 0.1204, 0.7509, 0.2399],
        [0.5718, 0.0033, 0.2118, 0.1296]])
tensor([0.7239, 0.5007, 0.0117, 0.5318, 0.7377, 0.1085, 0.5643, 0.0905, 0.4676,
        0.1204, 0.7509, 0.2399, 0.5718, 0.0033, 0.2118, 0.1296])


In [143]:
import torch
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [145]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [150]:
a=np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [159]:
if torch.cuda.is_available():
  device=torch.device("cuda")
  x=torch.ones(5,device=device)
  y=y.to(device)
  #z= x + y
  print(z)
  z=z.to("cpu")
  print(z)

tensor([[0.0886, 0.1250],
        [0.1359, 0.1652]])
tensor([[0.0886, 0.1250],
        [0.1359, 0.1652]])
